import { GetServerSideProps, NextPage } from 'next'
import { fetchArticles, fetchCategories } from '../http'
import { IArticle, ICategory, ICollectionResponse, IPropType } from '../types'
import { AxiosResponse } from 'axios'
import Head from 'next/head'
import Tabs from '../components/Tabs'
import ArticlesList from '../components/ArticlesList'

export const getServerSideProps: GetServerSideProps = async () => {
  //To Get Props from Server Side and return Props as object "categories:{item:categories.data}" 
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> = await fetchCategories()
  // console.log('Category => ', categories) // Whole fecth all data in category
  // console.log('Title =>', categories.data[0].attributes.Title) // fetch only Title

  //To Get Props from Server Side and return Props as object "aricles:{item:articles.data}" 
  const { data: articles }: AxiosResponse<ICollectionResponse<IArticle>> = await fetchArticles()


  return {
    props: {
      categories: {
        items: categories.data
      },
      articles:{
        items: articles.data,
        pagination: articles.meta.pagination
      }
    }
  }
}


const Home: NextPage<IPropType> = ({ categories, articles }) => {
  // console.log('Category => ', categories) // Whole fecth all data in category
  return (
    <div>
      <Head>
        <title>Coder Blog Next.Js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/m.png" />
      </Head>

      {/* Category  */}
      <Tabs categories={categories.items} />

      {/* Articales */}
      <ArticlesList articles={articles.items} />


    </div>
  )
}

export default Home





